# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: statistics-schedule

on:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cos-python-sdk-v5
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run Python scripts
      run: |
        python ./update.py
    - name: Commit to GitHub
      run: |
        export TZ CST-8 && git add . && git commit -m "Statistics of $(date -d "1 day ago" +"%y%m%d")" && git push --force
